name: coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
    
    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 15.x
      uses: actions/setup-node@v3
      with:
        node-version: 15.x
    - name: Installing dependencies
      run: npm install
    - name: Generating coverage information
      run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}